name: dog food

on: [push, pull_request, workflow_dispatch]

jobs:
  check-users-org:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run GitUsersOrg
        id: gituserorg
        uses: ./
        with:
          organization: 'PopcornPalace'
          token: ${{ secrets.ORG_TOKEN }}
